# Generated by Django 3.2.14 on 2022-07-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scramapp', '0002_scram_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scram',
            old_name='is_public',
            new_name='private',
        ),
    ]
